class ArtistTable(object):
    ARTIST_ID = "id"
    NAME = "name"
    URI = "uri"
    GENRES = "genres"

class AudioFeaturesTable(object):
    ANALYSIS_URL = "analysis_url"
    URI = "uri"
    TRACK_HREF = "track_href" 
    ACOUSTICNESS = "acousticness"
    DANCEABILITY = "danceability"
    DURATION_MS = "duration_ms"
    ENERGY = "energy"
    INSTRUMENTALNESS = "instrumentalness"
    LIVENESS = "liveness"
    LOUDNESS = "loudness"
    SPEECHINESS = "speechiness"
    TEMPO = "tempo"
    TIME_SIGNATURE  = "time_signature"
    VALENCE = "valence"
    KEY = "key"
    MODE = "mode"
    TYPE = "type"  


class PlaylistTable(object):
    PLAYLISTS = "playlists"
    COLLABORATIVE = "collaborative"
    DESCRIPTION = "description"
    DURATION_MS = "duration_ms"
    MODIFIED_AT = "modified_at"
    NAME = "name"
    NUM_ALBUMS = "num_albums"
    NUM_ARTISTS = "num_artists"
    NUM_EDITS = "num_edits"
    NUM_FOLLOWERS = "num_followers"
    NUM_TRACKS = "num_tracks"
    PID = "pid"
    TRACKS = "tracks"
    ALBUM_NAME = "album_name"
    ALBUM_URL = "album_url"
    ARTIST_NAME = "artist_name"
    ARTIST_URL = "artist_uri"
    TRACK_DURATION_MS = "duration_ms"
    POS = "pos"
    TRACK_NAME = "track_name"
    TRACK_URI = "track_uri"